### PR TITLE
Removed duplicate DE locale in Calendar

### PR DESCRIPTION
**Pull request by melloware**
Based on this forum post: https://forum.primefaces.org/viewtopic.php?f=3&t=61230

Also @christophs78 Look at the DatePicker example https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml

Why does the 'es' theme use `firstDayOfWeek: 1` and the 'de' example uses `firstDay: 1`???

### CODE REVIEW

**Comment by tandraschko** [comment]
+1

**Comment by christophs78** [comment]
> Why does the 'es' theme use `firstDayOfWeek: 1` and the 'de' example uses `firstDay: 1`???

firstDay should be right when we look into https://github.com/primefaces/primefaces/wiki/Locales. I think the ES-locale with the wrong firstDayOfWeek was already there since before my time. We should fix it too. :-)

**Comment by melloware** [comment]
When I look at DatePicker source code it has this...

```javascript
getSundayIndex: function () {
            var firstDayOfWeek = this.options.locale.firstDay !== undefined ? this.options.locale.firstDay : this.options.locale.firstDayOfWeek;
            return firstDayOfWeek > 0 ? 7 - firstDayOfWeek : 0;
        },
```

So it has BOTH values in locale.

**Comment by christophs78** [comment]
Maybe firstDayOfWeek was renamed to firstDay at some point in time. And to keep backward-compatibility DatePicker-JS still supports both.
In https://github.com/primefaces/primefaces/wiki/Locales i can´t find firstDayOfWeek anymore.

**Pull request merged**
