### PR TITLE
Use PF Cookie Handling

### PR DESCRIPTION
**Pull request by melloware**
The Showcase layout.js uses cookies to handle Menu state and whether to show the top advertisement bar.

- removes jQuery Cookie Pugin
- uses PF Builtin cookie mechanisms added in PF9
- will handle secure and Samesite token when running in Production automatically.

### CODE REVIEW

**Comment by tandraschko** [comment]
we should use localStorage for expanded stuff, not cookies actually

**Comment by melloware** [comment]
I thought of that too but wasn't sure whether to do it.  i will fix that today.

**Comment by tandraschko** [comment]
same for all other cookies actually
in best case cookies should only be used when also used on both server and client side

**Comment by melloware** [comment]
Agreed I will look and see where cookies are used in the showcase.  I know in PF we have switched everything we can to localStorage.

**Pull request merged**
