### PR TITLE
Lighthouse: efficiently encode images

### PR DESCRIPTION
**Pull request by melloware**
From Lighthouse report all of our images were containing extra info or not optimized.

See: https://web.dev/use-imagemin-to-compress-images/

Also removed images from /crop directory as those are temp images.

### CODE REVIEW

**Comment by tandraschko** [comment]
you checked that some are even bigger now?

**Comment by melloware** [comment]
Which are bigger?

**Comment by melloware** [comment]
Ahhh yes I see. that is really strange

**Comment by melloware** [comment]
Will fix.

**Pull request merged**
