### PR TITLE
CDI fixes based on warnings from Weld

### PR DESCRIPTION
**Pull request by melloware**
Running with the latest Weld in debug mode spit out a lot of warnings like the following. This PR fixes all the CDI warnings.

```
 Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field org.primefaces.showcase.view.dnd.DNDProductsView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.RowGroupView#service,
        - @Inject field org.primefaces.showcase.view.data.tree.SelectionView#service,
        - @Inject field org.primefaces.showcase.convert.ThemeConverter#themeService,
        - @Inject field org.primefaces.showcase.view.dnd.ColumnManagerView#service,
        - @Inject field org.primefaces.showcase.view.misc.ThemeSwitcherView#service,
        - @Inject field org.primefaces.showcase.view.data.ScheduleJava8View#extenderService,
        - @Inject field org.primefaces.showcase.view.data.treetable.MultiViewStateView#service,
        - @Inject field org.primefaces.showcase.convert.LocaleConverter#countryService,
        - @Inject field org.primefaces.showcase.view.data.datatable.BasicView#service,
        - @Inject field org.primefaces.showcase.view.input.SelectOneView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.LazyView#service,
        - @Inject field org.primefaces.showcase.view.input.SelectOneMenuView#service,
        - @Inject field org.primefaces.showcase.view.data.dataexporter.LazyView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.ScrollView#service,
        - @Inject field org.primefaces.showcase.view.df.DFProductsView#service,
        - @Inject field org.primefaces.showcase.view.data.dataexporter.CustomizedDocumentsView#service,
        - @Inject field org.primefaces.showcase.view.data.dataexporter.DataExporterView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.SortView#service,
        - @Inject field org.primefaces.showcase.view.data.tree.EventsView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.FilterView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.EventsView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.EditView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.BasicView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.MultiViewStateView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.ContextMenuView#service,
        - @Inject field org.primefaces.showcase.view.data.CarouselView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.CrudView#productService,
        - @Inject field org.primefaces.showcase.view.data.datatable.ReorderView#service,
        - @Inject field org.primefaces.showcase.view.data.tree.IconView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.ContextMenuView#service,
        - @Inject field org.primefaces.showcase.view.misc.SkeletonView#productService,
        - @Inject field org.primefaces.showcase.view.data.datatable.PaginatorView#service,
        - @Inject field org.primefaces.showcase.view.data.datalist.DataListView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.AddRowView#service,
        - @Inject field org.primefaces.showcase.view.input.SelectManyView#service,
        - @Inject field org.primefaces.showcase.view.data.tree.ContextMenuView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.ScrollableView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.ColumnsView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.SummaryRowView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.ResizableColumnsView#service,
        - @Inject field org.primefaces.showcase.view.data.DataScrollerView#service,
        - @Inject field org.primefaces.showcase.view.input.AutoCompleteView#countryService,
        - @Inject field org.primefaces.showcase.view.data.treetable.SelectionView#service,
        - @Inject field org.primefaces.showcase.view.data.OrderListView#service,
        - @Inject field org.primefaces.showcase.view.data.treetable.ColumnsView#service,
        - @Inject field org.primefaces.showcase.view.data.DataGridView#service,
        - @Inject field org.primefaces.showcase.convert.CountryConverter#countryService,
        - @Inject field org.primefaces.showcase.view.data.PickListView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.StickyView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.EditView#service,
        - @Inject field org.primefaces.showcase.view.data.datatable.SelectionView#service,
        - @Inject field org.primefaces.showcase.rest.CountryService#service
   ```

### CODE REVIEW

**Comment by tandraschko** [comment]
-1
Dont know why weld suggest this

**Comment by melloware** [comment]
Yeah I see that and their reason is this:
"And if Quarkus DI needs to access a private member it has to use reflection. That’s why Quarkus users are encouraged not to use private members in their beans. This involves injection fields, constructors and initializers, observer methods, producer methods and fields, disposers and interceptor methods."

I wonder if all CDI has to use reflection for private fields or whether its only Quarkus?

**Comment by tandraschko** [comment]
Sure reflection is required but its fast as hell. Quarkus just cant use reflection in native Image, thats the reason

**Comment by melloware** [comment]
ahhh that makes sense.

**Pull request closed without merging**
