### PR TITLE
Progressbar 364

### PR DESCRIPTION
**Pull request by ritonglue**
- longRunning function was not called. Removing the type "button" solves the problem.
- updateProgress must be removed from getProgress2
- The integer progress2 must be thread safe

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
I see what you mean

**Comment by ritonglue** [comment]
Thanks,
It took me hours to figure it out how to solve it. By chance I removed the 'type="button"' and it worked.
The next step is to launch the "longRunning" task in a separate thread like in a regular desktop application.

**Comment by melloware** [comment]
I am not sure running it it's own thread is necessary for demo purposes it's just to show a delay?

**Comment by ritonglue** [comment]
It's not necessary for demo purposes. In a desktop application if you don't launch the lengthy task in a separate thread, you'll freeze the screen.

**Comment by ritonglue** [comment]
I use `synchronized` to protect the variable `progress2`. It's possible that `volatile` would work.

**Comment by melloware** [comment]
Not necessary in a JSF view scoped bean. Only 1 thread can access at a time.  Very different from desktop apps.

**Pull request merged**
