### PR TITLE
MultiViewState ClientWindow instead of session

### PR DESCRIPTION
**Pull request by christophs78**
PF-PR: https://github.com/primefaces/primefaces/pull/6021

We need to think whether we want to activate this for Showcase. If yes i need to update all template.xhtml´s.

### CODE REVIEW

**Comment by christophs78** [comment]
@tandraschko : I like this idea too! On long term this should be part of JSF. Until this happens PrimeFaces should bring this solution. (This should also help organisations like mine who combine JSF with Spring.)

**Comment by christophs78** [comment]
@tandraschko : Do you plan to work on porting the relevant parts of DeltaSpike to PrimeFaces for the 9.0-release? (I would expect you know them already. So it may be easier for you to do this than for a DeltaSpike-newbie.)

**Comment by tandraschko** [comment]
i can atleast port the lazy mode very easy: https://deltaspike.apache.org/documentation/jsf.html#LAZY

we can even enhance it to use the session store nowadays instead of window.name

**Comment by melloware** [comment]
@christophs78 do you want to update this pr and test with @tandraschko new implementation of Window handling?

**Comment by christophs78** [comment]
Yes i´ll update this PR.

**Pull request merged**
