### PR TITLE
Accessible bread crumb style example

### PR DESCRIPTION
**Pull request by jepsar**
CSS example for https://github.com/primefaces/primefaces/issues/4928

### CODE REVIEW

**Comment by jepsar** [comment]
I don't think this should be merged (as is), but it provides an example of how the accessible bread crumb could be styled.

**Comment by jepsar** [comment]
@melloware note that there are sections for the component, theme and a custom part to add the chevron

**Comment by melloware** [comment]
Pinged you on Gitter...

**Comment by jepsar** [comment]
@mertsincan can this PR be removed?

**Comment by melloware** [comment]
Yes you can drop this PR Mert will fix the showcase.

**Pull request closed without merging**
